FROM gitlab.webini.fr:8444/totodl/nvidia/arm64/node:10.19.0

ARG VERSION
ENV NODE_ENV production
ENV PORT 3000

COPY --chown=node:node "." "/home/node/server"

USER node
WORKDIR /home/node/server

RUN touch .env && \
    npm i

ENTRYPOINT [ "node", "./run.js" ]

CMD [ "server" ]
