# docker-compose.yml
version: '3.1'

services:
  api:
    build: ./
    image: transcoder-api
    depends_on:
      - redis
    links:
      - redis:redis.host
    environment:
      REDIS_HOST: redis.host
      NODE_ENV: development
    volumes:
      - ./:/home/node/server
      - ${STORAGE_PATH}/virtual_storage:/home/node/virtual_storage
    ports:
      - 4000:${PORT}
    entrypoint: 'node'
    command: ['node_modules/.bin/nodemon', 'run.js', 'server']

  arena:
    image: transcoder-api
    depends_on:
      - api
      - redis
    environment:
      REDIS_HOST: redis.host
      ARENA_HOST: 0.0.0.0
    ports:
      - 4001:${ARENA_PORT}
    links:
      - redis:redis.host
    volumes:
      - ./:/home/node/server
      - ${STORAGE_PATH}/virtual_storage:/home/node/virtual_storage
    command: ['arena']

  transco-worker:
    image: transcoder-api
    depends_on:
      - redis
    links:
      - redis:redis.host
      - echo:echo.host
    environment:
      REDIS_HOST: redis.host
      NODE_ENV: development
    volumes:
      - ./:/home/node/server
      - ${STORAGE_PATH}/virtual_storage:/home/node/virtual_storage
    entrypoint: 'node'
    command: ['node_modules/.bin/nodemon', 'run.js', 'worker']

  redis:
    image: redis:5.0.5
    volumes:
      - ${STORAGE_PATH}/redis:/data
    command: redis-server --appendonly yes

  echo:
    image: mendhak/http-https-echo:18
    environment:
      HTTP_PORT: 80
      HTTPS_PORT: 443
