# docker-compose.yml
version: '3.1'

services:
  api:
    build: ./
    image: transcoder-api
    depends_on:
      - redis
    links:
      - redis:redis.host
    environment:
      REDIS_HOST: redis.host
      NODE_ENV: development
    volumes:
      - ./:/home/node/server
    ports:
      - 3000:3000
    entrypoint: 'node'
    command: ['node_modules/.bin/nodemon', 'run.js', 'server']

  arena:
    image: transcoder-api
    depends_on:
      - api
      - redis
    environment:
      REDIS_HOST: redis.host
      ARENA_PORT: 3000
      ARENA_HOST: 0.0.0.0
    ports:
      - 3001:3000
    links:
      - redis:redis.host
    volumes:
      - ./:/home/node/server
    command: ['arena']

  transco-worker:
    image: transcoder-api
    depends_on:
      - redis
    links:
      - redis:redis.host
    environment:
      REDIS_HOST: redis.host
      NODE_ENV: development
    volumes:
      - ./:/home/node/server
    entrypoint: 'node'
    command: ['node_modules/.bin/nodemon', 'run.js', 'worker']

  redis:
    image: redis:5.0.5
    volumes:
      - ${STORAGE_PATH}/redis:/data
    command: redis-server --appendonly yes
